//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectOnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_libraryEntities : DbContext
    {
        public db_libraryEntities()
            : base("name=db_libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_room> tb_room { get; set; }
        public virtual DbSet<tb_seat> tb_seat { get; set; }
        public virtual DbSet<tb_seat_student> tb_seat_student { get; set; }
        public virtual DbSet<tb_student> tb_student { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<MessageModels> MessageModels { get; set; }
    }
}
