//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectOnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_room()
        {
            this.tb_seat = new HashSet<tb_seat>();
            this.tb_seat_student = new HashSet<tb_seat_student>();
        }
        [Display(Name ="自习室编号")]
        public short no { get; set; }
        [Display(Name = "自习室名称")]
        public string name { get; set; }
        [Display(Name = "桌子数")]
        public Nullable<int> tables { get; set; }
        [Display(Name = "当前座位数")]
        public Nullable<int> cur { get; set; }
        [Display(Name = "15分钟后座位数")]
        public Nullable<int> after15min { get; set; }
        [Display(Name = "座位总数")]
        public Nullable<int> total { get; set; }
        [Display(Name = "可预约座位数")]
        public Nullable<int> book { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_seat> tb_seat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_seat_student> tb_seat_student { get; set; }
    }
}
