//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectOnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_seat_student
    {
        public string no { get; set; }
        public Nullable<short> room { get; set; }
        public Nullable<int> seat_no { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
        public Nullable<bool> isoutdate { get; set; }
        public Nullable<bool> issend_5_message { get; set; }
        public Nullable<bool> issend_20_message { get; set; }
    
        public virtual tb_room tb_room { get; set; }
        public virtual tb_seat tb_seat { get; set; }
        public virtual tb_student tb_student { get; set; }
    }
}
