//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectOnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_student
    {
        [Display(Name = "学号")]
        public string no { get; set; }
        [Display(Name = "一卡通ID")]
        public string card { get; set; }
        [Display(Name = "姓名")]
        public string name { get; set; }
        [Display(Name = "年级")]
        public Nullable<int> grade { get; set; }
        [Display(Name = "微信ID")]
        public string wechat { get; set; }
        [Display(Name = "系所")]
        public string department { get; set; }
        [Display(Name = "学院")]
        public Nullable<int> college { get; set; }
        [Display(Name = "班级")]
        public string @class { get; set; }
        [Display(Name = "小程序ID")]
        public string weapp { get; set; }
    
        public virtual tb_seat_student tb_seat_student { get; set; }
        public virtual tb_order tb_order { get; set; }
    }
}
